### ISSUE TITLE
Slow to reconnect after a Redis failover

### ISSUE THREAD

**Issue by davidor** [Kuadrant/limitador#16] opened 2021-02-01 14:13 UTC
In some tests that I ran together with @slopezz , we observed that Limitador was slow to reconnect after a Redis failover. The tests were using the async-redis storage implementation.

**Comment by alexsnaps** [comment] 2022-08-24 13:56
Let's look into this as part of the perf/QA efforts. We need to have scenarios that tests for these "failures"

**Comment by maleck13** [comment] 2024-10-02 07:32
@alexsnaps are you still hoping to address this in v1?

**Comment by alexsnaps** [comment] 2024-10-09 12:45
I couldn't reproduce this... so closing.

**Closed by alexsnaps** 2024-10-09 12:45 UTC
Labels: status/discussing, area/library, target/next
